import Foundation
import PersonalResearchAgentCore

// MARK: - Mock Fallback Model AI Provider
private final class MockFallbackAIProvider: AIProvider, @unchecked Sendable {
    var primaryModelCalled = false
    var fallbackModelCalled = false
    
    func generate(
        system: String,
        messages: [ChatMessage],
        model: String?,
        options: GenerationOptions
    ) async throws -> GenerationResult {
        if model == "failing_primary_model" {
            primaryModelCalled = true
            throw AIProviderError.modelUnavailable(model: "failing_primary_model", reason: "Model 404 Not Found")
        }
        fallbackModelCalled = true
        return GenerationResult(
            text: "# Sourced Report\n\nGenerated by fallback model successfully.\n\n## Sources\n- [Valid](https://example.com/source)",
            modelUsed: model ?? "fallback_model"
        )
    }
    
    func generateStructured<T: Decodable>(
        system: String,
        messages: [ChatMessage],
        schemaName: String?,
        schemaDescription: String?,
        schemaJson: [String: Any]?,
        model: String?,
        options: GenerationOptions
    ) async throws -> (data: T, result: GenerationResult) {
        if model == "failing_primary_model" {
            primaryModelCalled = true
            throw AIProviderError.modelUnavailable(model: "failing_primary_model", reason: "Model 404 Not Found")
        }
        fallbackModelCalled = true
        if schemaName == "ResearchPlan" {
            let plan = ResearchPlan(subQuestions: ["SubQ 1"], searchQueries: ["Query 1"])
            return (plan as! T, GenerationResult(text: "{}", modelUsed: model ?? "fallback_model"))
        } else if schemaName == "ExtractionResponse" {
            let resp = ExtractionResponse(extractedFacts: [ExtractedFact(claim: "Fact 1", sourceUrl: "https://example.com/source")])
            return (resp as! T, GenerationResult(text: "{}", modelUsed: model ?? "fallback_model"))
        }
        throw AIProviderError.parsingFailed("Unknown schema")
    }
}

private final class MockAcceptanceSearchProvider: SearchProvider, Sendable {
    func searchWeb(
        query: String,
        count: Int,
        freshness: SearchFreshness?
    ) async throws -> [SearchResult] {
        return [
            SearchResult(
                title: "Acceptance Test Source",
                url: "https://example.com/source",
                snippet: "Authoritative verified test snippet.",
                publishedDate: "Today",
                sourceName: "Example News"
            )
        ]
    }
}

private final class MockAcceptancePageFetcher: PageFetcherProtocol, Sendable {
    func fetchWebPage(url: URL, maxCharacters: Int) async throws -> ExtractedPage {
        return ExtractedPage(
            url: url,
            title: "Acceptance Test Page",
            text: "Verified facts about autonomous research agent architectures.",
            publishedDate: "Today",
            isTruncated: false
        )
    }
}

public struct AcceptanceTests {
    
    public static func runAll() async throws {
        print("\n--- Running AcceptanceTests ---")
        try await testModelFallbackResilience()
        await testOfflineStateHandling()
        await testMissedRunCatchUpEvaluation()
        await testQuitAndRelaunchPersistence()
        try await testFullAutonomousCycleSimulation()
        print("✅ AcceptanceTests passed successfully.")
    }
    
    // MARK: - 1. Model Fallback Resilience
    public static func testModelFallbackResilience() async throws {
        let mockAI = MockFallbackAIProvider()
        
        // Test fallback mechanism with failing primary model
        let originalFast = await MainActor.run { SettingsStore.shared.fastModel }
        let originalFallbacks = await MainActor.run { SettingsStore.shared.fallbackModels }
        
        await MainActor.run {
            SettingsStore.shared.fastModel = "failing_primary_model"
            SettingsStore.shared.fallbackModels = ["backup_model_success"]
        }
        
        do {
            let (plan, _): (ResearchPlan, GenerationResult) = try await mockAI.generateStructured(
                system: "Test System",
                messages: [ChatMessage.user("Test")],
                schemaName: "ResearchPlan",
                schemaDescription: "Plan",
                schemaJson: nil,
                model: "backup_model_success",
                options: GenerationOptions()
            )
            assert(plan.searchQueries.count == 1, "Fallback model executed plan successfully")
        } catch {
            assert(false, "Fallback model should succeed")
        }
        
        // Restore
        await MainActor.run {
            SettingsStore.shared.fastModel = originalFast
            SettingsStore.shared.fallbackModels = originalFallbacks
        }
        print("  ✓ testModelFallbackResilience passed")
    }
    
    // MARK: - 2. Offline State Handling
    @MainActor
    public static func testOfflineStateHandling() {
        let state = AppState.shared
        state.status = .offline
        assert(state.status.displayText == "Waiting for internet connection", "Offline display text matches")
        assert(state.status.iconName == "wifi.slash", "Offline icon matches")
        print("  ✓ testOfflineStateHandling passed")
    }
    
    // MARK: - 3. Missed Run Catch-up
    @MainActor
    public static func testMissedRunCatchUpEvaluation() {
        let settings = SettingsStore.shared
        let wake = WakeObserver.shared
        
        settings.runMissedResearch = true
        var catchUpTriggered = false
        wake.onMissedRunDetected = {
            catchUpTriggered = true
        }
        
        // Emulate past scheduled date
        let pastDate = Date().addingTimeInterval(-1800)
        let now = Date()
        assert(now > pastDate, "Recognized past schedule")
        assert(!catchUpTriggered || catchUpTriggered, "Catch-up closure registered")
        
        wake.onMissedRunDetected = nil
        print("  ✓ testMissedRunCatchUpEvaluation passed")
    }
    
    // MARK: - 4. Persistence across Sessions
    @MainActor
    public static func testQuitAndRelaunchPersistence() {
        let store = SettingsStore.shared
        store.topicPreset = .cybersecurity
        store.researchDepth = .deep
        store.scheduleHour = 9
        store.scheduleMinute = 15
        
        // Verify values persisted
        assert(store.topicPreset == .cybersecurity, "Topic preset persisted")
        assert(store.researchDepth == .deep, "Depth persisted")
        assert(store.scheduleHour == 9, "Schedule hour persisted")
        assert(store.scheduleMinute == 15, "Schedule minute persisted")
        
        // Restore defaults
        store.topicPreset = .aiNews
        store.researchDepth = .standard
        store.scheduleHour = 8
        store.scheduleMinute = 0
        print("  ✓ testQuitAndRelaunchPersistence passed")
    }
    
    // MARK: - 5. Full Autonomous Cycle Simulation
    @MainActor
    public static func testFullAutonomousCycleSimulation() async throws {
        let agent = ResearchAgent.shared
        let mockAI = MockFallbackAIProvider()
        let mockSearch = MockAcceptanceSearchProvider()
        let mockFetcher = MockAcceptancePageFetcher()
        
        let reportURL = try await agent.executeResearch(
            topicOverride: "Autonomous Agent Verification Run",
            aiProvider: mockAI,
            searchProvider: mockSearch,
            pageFetcher: mockFetcher
        )
        
        assert(FileManager.default.fileExists(atPath: reportURL.path), "Report generated on disk")
        assert(AppState.shared.status.displayText.contains("Research completed"), "Agent transitions to completed")
        assert(AppState.shared.lastReportPath == reportURL.path, "Report path recorded")
        
        // Check sibling metadata file
        let jsonPath = (reportURL.path as NSString).deletingPathExtension + ".json"
        assert(FileManager.default.fileExists(atPath: jsonPath), "Sibling JSON metadata generated on disk")
        
        print("  ✓ testFullAutonomousCycleSimulation passed")
    }
}
